### ISSUE TITLE
Unnecessary dependencies

### ISSUE THREAD

**Issue by hybridvision** [nicolas-cusan/tailwind-clamp#4]
Hello again @nicolas-cusan,

Earlier when I was testing some things, I noticed that it was quite slow to install this plugin as a dependency. I see why now: it's including `next`, `react`, `react-dom` and `autoprefixer`, which I don't think are actually needed. Can you please confirm?

**Comment by nicolas-cusan** [comment]
Hello @hybridvision

Yes, these are used for development. I moved them to `devDependencies`. Hope this helps. I use next for the development of the plugin.
